name: sonarr
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    stop_grace_period: 2m
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config:/config
      - ${MEDIA_DIR}:/data

    ports:
      - "8989:8989"
    restart: unless-stopped
    networks:
      - default

networks:
  default:
    name: caddy_net
    external: true


