services:
  mc:
    container_name: mc
    image: itzg/minecraft-server:latest
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
      - "24454:24454/udp"
      - "8100:8080"
    environment:
      EULA: "TRUE"
      TYPE: FABRIC
      JAVA_VERSION: 21
      VERSION: "1.21.11"
      MEMORY: "10240M"
      MAX_PLAYERS: "10"
      MOTD: "\u00a7r           \u00a7f\u00a7lSurvival\u00a7f \u00a7oForever World\u00a7f  [1.12.11]\u00a7r\n\u00a7f\u00a7l              Network: \u00a79\u00a7n\u00a7olacto.vip"
      TZ: "America/Santiago"
      DIFFICULTY: "3"
      FORCE_GAMEMODE: "true"
      ENTITY_BROADCAST_RANGE_PERCENTAGE: "175"
      SIMULATION_DISTANCE: "12"
      VIEW_DISTANCE: "12"
      ENABLE_WHITELIST: "true"
    volumes:
      - "./data:/data"
    networks:
      - default

networks:
  default:
    name: caddy_net
    external: true
