services:
  byparr:
    image: ghcr.io/thephaseless/byparr:latest
    container_name: byparr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - "8191:8191"
    restart: unless-stopped
    networks:
      - default

networks:
  default:
    name: caddy_net
    external: true
