name: bazarr
services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    stop_grace_period: 2m
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config:/config
      - ${MEDIA_DIR}:/data

    ports:
      - "6767:6767"
    restart: unless-stopped
    networks:
      - default

networks:
  default:
    name: caddy_net
    external: true


