---
- Applications:
    - Jellyfin:
        icon: jellyfin.png
        href: "https://tv.lacto.vip"
        description: "Media Server"
        widget:
            type: jellyfin
            url: https://tv.lacto.vip
            key: "{{HOMEPAGE_VAR_JELLYFIN_API_KEY}}"

    - Immich:
        icon: immich.png
        href: "https://photos.lacto.vip"
        description: "Photos & Videos"
        widget:
            type: immich
            url: http://immich-server:2283
            key: "{{HOMEPAGE_VAR_IMMICH_API_KEY}}"
            version: 2

    - Jellyseerr:
        icon: jellyseerr.png
        href: "https://requests.lacto.vip"
        description: "Movies & TV Requests"
        widget:
            type: jellyseerr
            url: http://jellyseerr:5055
            key: "{{HOMEPAGE_VAR_JELLYSEERR_API_KEY}}"

    - Filebrowser:
        icon: filebrowser.png
        href: "https://drive.lacto.vip"
        description: "Private Cloud"
        widget:
            type: customapi
            url: http://filebrowser:80/health
            refreshInterval: 10000

- Media & Downloads:
    - Radarr:
        icon: radarr.png
        href: "https://movies.lacto.vip"
        description: "Movie Management"
        widget:
            type: radarr
            url: http://radarr:7878
            key: "{{HOMEPAGE_VAR_RADARR_API_KEY}}"

    - Sonarr:
        icon: sonarr.png
        href: "https://series.lacto.vip"
        description: "TV Show Management"
        widget:
            type: sonarr
            url: http://sonarr:8989
            key: "{{HOMEPAGE_VAR_SONARR_API_KEY}}"

    - qBittorrent:
        icon: qbittorrent.png
        href: "https://torrent.lacto.vip/"
        description: "Torrent Client"
        widget:
            type: qbittorrent
            url: http://qbittorrent:8080
            username: "{{HOMEPAGE_VAR_ADMIN_USER}}"
            password: "{{HOMEPAGE_VAR_ADMIN_PASS}}"

    - Prowlarr:
        icon: prowlarr.png
        href: "https://prowlarr.lacto.vip"
        description: "Indexer Manager"
        widget:
            type: prowlarr
            url: http://prowlarr:9696
            key: "{{HOMEPAGE_VAR_PROWLARR_API_KEY}}"

    - Bazarr:
        icon: bazarr.png
        href: "https://subs.lacto.vip"
        description: "Subtitle Management"
        widget:
            type: bazarr
            url: http://bazarr:6767
            key: "{{HOMEPAGE_VAR_BAZARR_API_KEY}}"

- Infrastructure:
    - Nginx Proxy:
        icon: nginx-proxy-manager.png
        href: "https://nginx.lacto.vip"
        description: "Reverse Proxy"
        widget:
            type: npm
            url: http://nginx:81
            username: "{{HOMEPAGE_VAR_ADMIN_EMAIL}}"
            password: "{{HOMEPAGE_VAR_ADMIN_PASS}}"

    - AdGuard DNS:
        icon: adguard-home.png
        href: "https://adguard.lacto.vip"
        description: "DNS & Ad Blocker"
        widget:
            type: adguard
            url: http://adguard:8083
            username: "{{HOMEPAGE_VAR_ADMIN_USER}}"
            password: "{{HOMEPAGE_VAR_ADMIN_PASS}}"

    - Tailscale:
        icon: tailscale.png
        href: "https://login.tailscale.com/admin/machines"
        description: "VPN Management"

- Gaming:
    - Minecraft Map:
        icon: minecraft.png
        href: "https://map.lacto.vip"
        description: "Live Server Map"

    - Modpack Download:
        icon: mdi-folder-download
        href: "https://drive.lacto.vip/share/a5E8RutE"
        description: "Modpack Share Page"
        ping: http://filebrowser:80
