---
title: "Homelab"
theme: dark

layout:
  - Media:
      style: row
      columns: 3
  - Arr Stack:
      style: row
      columns: 2
  - Infrastructure:
      style: row
      columns: 3
  - Games:
      style: row
      columns: 3
  - External:
      style: row
      columns: 2
