---
title: "Homelab"
theme: dark

layout:
  - Applications:
      style: row
      columns: 2
  - Media & Downloads:
      style: row
      columns: 3
  - Gaming:
      style: row
      columns: 2
  - Infrastructure:
      style: row
      columns: 3
